-- How many lifetime hits does Barry Bonds have?

select sum(b.hits) as hits_lifetime
from players a
inner join stats b
on a.id=b.player_id
where first_name='Barry'
    and last_name='Bonds'
;

-- player_id for Barry Bonds is 1687

---Integery Primary Key is autogenerated sequential number, i.e. not a primary index like cm11
-- Expected result:
-- 2935


